name: 'Bark Action'
description: 'An action for bark'
author: 'Yihan G <crownor@nlp.ac> forked from Yuanhao Ji <jiyuanhao@apache.org>'
branding:
  icon: 'message-circle'
  color: 'red'
inputs:
  key:
    description: Secret key
    required: true
  host:
    description: Bark server hostname
    required: false
  title:
    description: Message title
    required: false
  body:
    description: Message body
    required: false
  sound:
    description: Message sound
    required: false
  isArchive:
    description: Whether to archive this message
    required: false
  url:
    description: URL to redirect
    required: false
  automaticallyCopy:
    description: Whether to copy this message automatically
    required: false
  copy:
    description: Content copied to clipboard
    required: false
  group:
    description: 指定推送消息分组，可在历史记录中按分组查看推送
    required: false
  icon:
    description: 指定推送消息图标
    required: false
  level:
    description: 设置时效性通知
    required: false

runs:
  using: "composite"
  steps:
    - name: Run script
      shell: bash
      run: $GITHUB_ACTION_PATH/script.sh
      env:
        INPUT_KEY: ${{ inputs.key }}
        INPUT_HOST: ${{ inputs.host }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_BODY: ${{ inputs.body }}
        INPUT_SOUND: ${{ inputs.sound }}
        INPUT_IS_ARCHIVE: ${{ inputs.isArchive }}
        INPUT_URL: ${{ inputs.url }}
        INPUT_AUTOMATICALLY_COPY: ${{ inputs.automaticallyCopy }}
        INPUT_COPY: ${{ inputs.copy }}
        INPUT_GROUP: ${{ inputs.group }}
        INPUT_ICON: ${{ inputs.icon }}
        INPUT_LEVEL: ${{ inputs.level }}
