name: 'Bark Action'
description: 'An action for bark'
author: Ji Yuanhao <jiyuanhao1997@gmail.com>
branding:
  icon: 'message-circle'
  color: 'red'
inputs:
  key:
    description: Secret key
    required: true
  title:
    description: Message title
    required: false
  body:
    description: Message body
    required: false
  sound:
    description: Message sound
    required: false
  isArchive:
    description: Whether to archive this message
    required: false
  url:
    description: URL to redirect
    required: false
  automaticallyCopy:
    description: Whether to copy this message automatically
    required: false
  copy:
    description: Content copied to clipboard
    required: false
runs:
  using: "composite"
  steps:
    - name: Echo inputs to environment variables
      shell: bash
      run: |
        echo "INPUT_KEY=${{ inputs.key }}" >> $GITHUB_ENV
        echo "INPUT_TITLE=${{ inputs.title }}" >> $GITHUB_ENV
        echo "INPUT_BODY=${{ inputs.body }}" >> $GITHUB_ENV
        echo "INPUT_SOUND=${{ inputs.sound }}" >> $GITHUB_ENV
        echo "INPUT_ISARCHIVE=${{ inputs.isArchive }}" >> $GITHUB_ENV
        echo "INPUT_URL=${{ inputs.url }}" >> $GITHUB_ENV
        echo "INPUT_AUTOMATICALLYCOPY=${{ inputs.automaticallyCopy }}" >> $GITHUB_ENV
        echo "INPUT_COPY=${{ inputs.copy }}" >> $GITHUB_ENV
    - name: Work
      shell: bash
      run: ${{ github.action_path }}/script.sh
