name: 'Push Notifications via Bark'

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest

    if: ${{ github.event.repository.owner.id == github.event.sender.id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push notification
        uses: ./
        with:
          key: ${{ env.KEY }}
          host: ${{ env.HOST }}
          title: Message title
          body: Message body
          sound: alarm
          isArchive: 1
          automaticallyCopy: 1
          copy: Content copied to clipboard
          icon: https://tvax3.sinaimg.cn//005J7Lxkly1hnqvgm7asgj30e80e8q4r.jpg
